version: "3"

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always

  house:
    depends_on:
      - redis
    image: local/pit-boss/the-house:2
    ports:
      - "2312:2312"
    restart: always

volumes:
  redis_data:
