version: "3.9"

services:
  keydb:
    image: eqalpha/keydb
    networks:
      - back-of-house

  the-house:
    build:
      context: ./the-house
      target: dev
      args:
        NODE_VERSION: 16
    environment:
      HTTP_PORT: 8080
      HTTP_HOST: 0.0.0.0
      DEBUG: "house"
      DEBUG_HIDE_DATE: "true"
      REDIS_URL: "redis://keydb:6379"
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./the-house/server
        target: /srv/server
    networks:
      - front-of-house
      - back-of-house


networks:
  front-of-house:
  back-of-house:

